### PR TITLE
Fixed language selector not showing up on click

### PR DESCRIPTION
**Pull request by CosmosAtlas**
As the titled stated, using the current `master` and set `showLanguageSelector = true` will display the language selector but unable to switches languages. 

This pull request contains changes to fix the issue.

### CODE REVIEW

**Comment by IsaEs** [comment]
thank you @CosmosAtlas

**Comment by panr** [comment]
Oh, crap. What happened in the `languageSelector.js` file... How did I allow this... 🤯 🙈 Thanks for spotting that 💩

**Comment by panr** [comment]
I've updated the code a little 👍

**Comment by CosmosAtlas** [comment]
Glad it gets merged. And thanks for creating the theme!

**Pull request merged**
