### PR TITLE
add KaTeX support as a community feature

### PR DESCRIPTION
**Pull request by amtoine**
hello there :wave: :yum: 

i wanted to have some beautiful formulae in my personal website and saw #224.
it appears it has never been added as a community feature in [`COMMUNITY-FEATURES.md`](https://github.com/panr/hugo-theme-terminal/blob/master/COMMUNITY-FEATURES.md) so here it is :blush: 

this is greatly inspired by [this blog post](https://petercheng.me/blog/rendering-latex-with-katex-in-a-hugo-blog/) :+1: 

- i've added some instructions at the [top of the README](https://github.com/amtoine/hugo-theme-terminal-katex#terminal)
- the changes added by the feature can be seen [here](https://github.com/amtoine/hugo-theme-terminal-katex/compare/9726b8d..master)

### CODE REVIEW

**Comment by amtoine** [comment]
@panr 
i'd love to know what's wrong with this PR :)
it's been a while so i don't remember all the details!

**Comment by panr** [comment]
Oh... so sorry. I missed that this is for Community 🙏

**Comment by panr** [comment]
Just merged it ✅ 
I just made a bulk PR cleanup when I started v4.0.0... Sorry once again :-(

**Comment by panr** [comment]
Yeah, I stopped maintaining of the theme for a year (was busy with other stuff)... Things got really rusty over that time...

**Pull request merged**
