### PR TITLE
Allow target="_blank" with .Params.NewTab set to true

### PR DESCRIPTION
**Pull request by matidfk**
example:
```
[[menu.main]]
identifier = "discord"
name = "Discord"
url = "https://discord.gg/..."
[menu.main.params]
    newTab = true
```

### CODE REVIEW

**Comment by aleskandro** [comment]
This patch is not anymore in the master branch. Any plan to re-include it?

**Comment by panr** [comment]
Yes, I will, but for now, you can do it yourself if you are using the latest version of the theme (which doesn't need a recompilation). Just copy/paste the missing code and you are good to go ;-)

**Comment by matidfk** [comment]
Oh, did I accidentally submit this to the wrong branch?

**Comment by panr** [comment]
No @matidfk, I've switched branches recently and it turned out that I didn't include your patch ;-(

**Comment by georg3tom** [comment]
@panr any plans to include this patch again?

**Comment by panr** [comment]
@georg3tom done https://github.com/panr/hugo-theme-terminal/commit/9726b8d80658c6cf3c092c21484548aba6f64a68

**Comment by icy-comet** [comment]
@panr how about using `.Param` function so that the preference can be set site-wide just in case?

**Pull request merged**
