### PR TITLE
feat(USERS): Add jiriks74

### PR DESCRIPTION
**Pull request by jiriks74**
Hello,
great theme!  I've been enjoying it for quite some time. Since I've decided to update my website a bit I've also updated to the newer version of the theme since you picked it back up. Great work!

I've added myself to USERS.md. I also noticed that **a lot** of websites in that file are either gone, using a different theme or not using Hugo anymore. I have a patch for the file with those deleted if you're interested.

> [!Note]
> I'm missing a thing that I liked quite a bit - the old tables with the dotted borders. I've used them as a cool little sub heading as the table could be stretched to the whole container, the text could be centered and the colored border consisting of `-` looked quite cool. Is there a way to get them back? I'd like to have them on my home page. I'll try to look for the stylesheet myself but if you still have it somewhere that would be cool.

### CODE REVIEW

**Comment by panr** [comment]
Hi, @jiriks74 👋 Could you append yourself to the list, like anyone else? :-D At the moment you are at the beginning.

Regarding the state of the list. I don't really care if the users still use the theme. For me, more important is that they used to use it. I treat it more like an archive of anyone who was interested in it, even for testing or something ;-)

**Comment by jiriks74** [comment]
> Hi, @jiriks74 👋 Could you append yourself to the list, like anyone else? :-D At the moment you are at the beginning.

Sure! I've been doing other edits (looking who's websites are not working anymore) and this slipped.

> I treat it more like an archive of anyone who was interested in it, even for testing or something ;-)

Sure! I looked into it with the *Hey! Look at the websites using this theme! It's good inspiration!* perspective and it was surprising that (I think) more than a half of the file is broken (non existent websites) and some others are using other themes or website engines. I was surprised at how many of the list was left.

I got some cool site that I'll get inspiration from.

**Comment by jiriks74** [comment]
How is this a conflict for god's sake?

**Comment by jiriks74** [comment]
I know that you probably don't want to deal with this but I got an idea that would work for both sides - you could have the `USERS.md` file with the active websites and if someone kills the site or uses something else you could then have them in something like `USERS-archive.md`. People then could easily look through the websites (as the start of the file wouldn't almost all be killed sites) and you'd have the archive.

Just an idea. It's not that big of a deal in the end and you should have it how you like it.

**Comment by panr** [comment]
I know that this file has become a little bit problematic, and probably the best idea is to get rid of it, because maintaining it doesn't make sense to be completely honest.

**Pull request merged**
