### PR TITLE
Update menu margin for visual align

### PR DESCRIPTION
**Pull request by soomtong**
## Summary

some visual align is not match number matric. for example, apple's round square icon.

in this case, shown below, a letter 'A' seems left out from left side guard. 

- get some trim a visual align for left and right 
- by adding a margin 1 px.

### before 

image

### after

image

### CODE REVIEW

**Comment by panr** [comment]
hey @soomtong, thanks for the PR. I recently made some changes to some global styles, so could you update your branch because of the conflicts? 🙏 

Also could you post here an image with the visual changes, like after / before comparison?

**Comment by soomtong** [comment]
> hey @soomtong, thanks for the PR. I recently made some changes to some global styles, so could you update your branch because of the conflicts? 🙏
> 
> Also could you post here an image with the visual changes, like before/after comparison?

OMG, i am sorry panr. I didnt know when i push this pr without request body (i m not a person doing like this!!! 😭 ). 
I guess i missed this system working something like automatic request to pull lol. 

but i got your kindness feedback and cares. I ll do make it right again. and this (your) theme so cool and lovely! for terminal holic users like me!

**Comment by soomtong** [comment]
hi @panr can you check this again?

**Comment by panr** [comment]
Merged, thanks 🎉

**Pull request merged**
