### PR TITLE
initial draft for gist syntax highlighting and table-layout modification

### PR DESCRIPTION
**Pull request by robbienohra**
Changed `table-layout` value to `auto` in `styles.css` to resolve [Issue With Gist Display #156
](https://github.com/panr/hugo-theme-terminal/issues/156). 

Also included `monokai` gist syntax highlighting sourced from [gist-syntax-themes/stylesheets/monokai.css](https://github.com/lonekorean/gist-syntax-themes/blob/master/stylesheets/monokai.css).

Demo: 

image

### CODE REVIEW

**Comment by panr** [comment]
Oh, the batch of changes is unreadable, so:

- could you add the styling for Gist as a separate CSS file. And I'd be nice to match the styling with the syntax color scheme provided by the theme. Monokai is OK, but I looks odd in the Terminal theme.
- in `style.css` change only the table styling

**Review by panr — CHANGES_REQUESTED** [review]
☝🏻

**Comment by robbienohra** [comment]
@panr makes sense!
will take care of it 😉

**Comment by panr** [comment]
> in style.css change only the table styling

Oh, and by `style.css` I meant `main.css`. Just figured out that you changed the production ready file, but you should go to the `assets/css` dir, where dev ready files are ;-)
Here's a link to `main.css` — https://github.com/panr/hugo-theme-terminal/blob/master/assets/css/main.css

And you can extend the `style.css` there by the new CSS file for the Gist styles ;-)

**Comment by robbienohra** [comment]
@panr thanks for the catch, got it!

**Comment by robbienohra** [comment]
making some progress 😉

image

**Comment by robbienohra** [comment]
@panr it looks like there are some language-specific cases that conflict with each other in terms of remaining consistent with the theme. 

For example the `pl-c1` example.

In the statement `const x = 1` in JS the element `1` has the class `pl-c1`. 

In the statement `top.pop()` in C++ the element `pop()` also has the class `pl-c1`.

So the color set for `pl-c1` would be applied to both elements. However with the terminal theme styling the `1` element has the color `var(--accent)` and the `pop()` element has the theme's gray `rgb(163, 155, 148)`.

We'll need to make judgement calls in these scenarios.

**Comment by robbienohra** [comment]
Otherwise I've gotten it pretty close to a one-to-one relationship with the terminal theme. But yeah might be worth poking around and letting me know for some of these split cases.

**Comment by smailzhu** [comment]
hmm it doesn't works for me
I execute
`git clone --branch feature/gist-syntax-highlighting git@github.com:robbienohra/hugo-theme-terminal.git themes/terminal-gist`
and
`hugo server -D -t terminal-gist`
but get same problem

**Comment by robbienohra** [comment]
so the thing is the files in the prod-ready static directory need to be regenerated to reflect the changes as well
need to see what the correct protocol for that is

**Comment by robbienohra** [comment]
@panr sorry if this is a stupid question lol
but what's the correct protocol for getting the _prod_ `static/assets/style.css` files to reflect the styles living in `assets/css/style.css`? 
is there a build CLI command that needs to be run?

**Comment by panr** [comment]
@robbienohra `yarn` to install deps and then `yarn build` ;-)

**Comment by panr** [comment]
I need to set some CI actions for this repo 😅

**Comment by robbienohra** [comment]
haha no worries lol
just ran the build and re-pushed so others can test
@smailzhu you can try now

**Comment by robbienohra** [comment]
@panr I'm starting to debate whether applying the full theme to the gists is maybe too ambitious lol
it may be better for me to revert it to just simply include the `table-layout` correction + removing the borders from the line numbers

**Comment by panr** [comment]
> @panr I'm starting to debate whether applying the full theme to the gists is maybe too ambitious lol
it may be better for me to revert it to just simply include the table-layout correction + removing the borders from the line numbers

Are you sure? Maybe you could split the scope of this PR and make 2:
- the one with table changes
- and the other one with gist color scheme changes (in no hurry) ;-)

**Comment by robbienohra** [comment]
sounds good 👍

**Comment by smailzhu** [comment]
Thanks a lot. It works for me.
btw personally I prefer original gist font ><

**Comment by robbienohra** [comment]
@smailzhu  lol yeah honestly the syntax highlighting was more experimental

I'm just going to reduce this PR to the `table-layout` fix and border removal around the line numbers

**Comment by robbienohra** [comment]
hey @panr I think this is ready to go
let me know if you see anything out of whack

**Comment by panr** [comment]
@robbienohra OK, I'm gonna check it later today 👍🏻

**Review by panr — APPROVED** [review]
Looks good. I hope you're not going to leave the Gist PR redesign and we will see it soon 😎

**Pull request merged**
