### PR TITLE
Add defaults to post archetype

### PR DESCRIPTION
**Pull request by zchrykng**

### CODE REVIEW

**Comment by panr** [comment]
I'm sorry, but why did you put `{{ .Date }}` variable in the author property?

**Review by panr — CHANGES_REQUESTED** [review]
Used variables don't make sense...

**Comment by zchrykng** [comment]
Dang, sorry. I was copying and pasting from somewhere else and must have not been paying attention. Changes coming soon.

**Comment by panr** [comment]
Cool, thanks!

**Pull request merged**
